DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS annual_pass_usage;
DROP TABLE IF EXISTS annual_pass_holder;
DROP TABLE IF EXISTS annual_pass;
DROP TABLE IF EXISTS annual_pass_plan;
DROP TABLE IF EXISTS user_coupon;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS animal;
DROP TABLE IF EXISTS zone;
DROP TABLE IF EXISTS activity_signup;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS checkin_record;
DROP TABLE IF EXISTS refund_record;
DROP TABLE IF EXISTS payment_record;
DROP TABLE IF EXISTS order_activity_item;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS reservation_order;
DROP TABLE IF EXISTS daily_ticket_inventory;
DROP TABLE IF EXISTS ticket_inventory;
DROP TABLE IF EXISTS ticket_type;
DROP TABLE IF EXISTS visitor_profile;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS admin_user;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  phone VARCHAR(32) UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL
);

CREATE TABLE permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(128) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  menu_path VARCHAR(255)
);

CREATE TABLE user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  UNIQUE (user_id, role_id, user_type)
);

CREATE TABLE visitor_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  real_name VARCHAR(64) NOT NULL,
  id_card_no VARCHAR(64) NOT NULL,
  phone VARCHAR(32),
  is_default TINYINT NOT NULL DEFAULT 0,
  UNIQUE (user_id, id_card_no)
);

CREATE TABLE ticket_type (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description VARCHAR(255),
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED'
);

CREATE TABLE ticket_inventory (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  visit_date DATE NOT NULL,
  session_code VARCHAR(32) NOT NULL,
  ticket_type_id BIGINT NOT NULL,
  capacity INT NOT NULL,
  remaining INT NOT NULL,
  UNIQUE (visit_date, session_code, ticket_type_id)
);

CREATE TABLE daily_ticket_inventory (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  visit_date DATE NOT NULL,
  ticket_type_id BIGINT NOT NULL,
  capacity INT NOT NULL,
  remaining INT NOT NULL,
  UNIQUE (visit_date, ticket_type_id)
);

CREATE TABLE reservation_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT,
  visit_date DATE NOT NULL,
  session_code VARCHAR(32) NOT NULL,
  order_type VARCHAR(32) NOT NULL DEFAULT 'TICKET',
  original_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  amount DECIMAL(10,2) NOT NULL,
  coupon_id BIGINT,
  annual_pass_id BIGINT,
  order_status VARCHAR(32) NOT NULL,
  payment_status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  ticket_type_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL
);

CREATE TABLE payment_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  payment_no VARCHAR(64) NOT NULL UNIQUE,
  channel VARCHAR(32) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(32) NOT NULL,
  callback_payload CLOB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refund_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  refund_no VARCHAR(64) NOT NULL UNIQUE,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(32) NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE checkin_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  checker_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(255),
  checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  capacity INT NOT NULL,
  location VARCHAR(128),
  is_paid TINYINT NOT NULL DEFAULT 0,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  coupon_scope VARCHAR(64) NOT NULL DEFAULT 'ACTIVITY',
  status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED'
);

CREATE TABLE activity_signup (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  activity_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  order_id BIGINT,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (activity_id, user_id)
);

CREATE TABLE order_activity_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  activity_id BIGINT NOT NULL,
  activity_title VARCHAR(128) NOT NULL,
  activity_category VARCHAR(64) NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL
);

CREATE TABLE zone (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(500),
  map_x DECIMAL(10,6),
  map_y DECIMAL(10,6)
);

CREATE TABLE animal (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  zone_id BIGINT,
  name VARCHAR(128) NOT NULL,
  species VARCHAR(128),
  description VARCHAR(500),
  media_url VARCHAR(500),
  status VARCHAR(32) NOT NULL DEFAULT 'VISIBLE'
);

CREATE TABLE coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  discount_type VARCHAR(32) NOT NULL,
  discount_value DECIMAL(10,2) NOT NULL,
  threshold_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_quantity INT,
  claimed_quantity INT NOT NULL DEFAULT 0,
  valid_from DATE,
  valid_to DATE,
  scope VARCHAR(64) NOT NULL DEFAULT 'TICKET',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED'
);

CREATE TABLE user_coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  coupon_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'UNUSED',
  order_id BIGINT,
  claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used_at TIMESTAMP,
  UNIQUE (user_id, coupon_id)
);

CREATE TABLE annual_pass_plan (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  valid_days INT NOT NULL,
  holder_limit INT NOT NULL,
  benefits VARCHAR(1000),
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED'
);

CREATE TABLE annual_pass (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  pass_no VARCHAR(64) NOT NULL UNIQUE,
  started_at DATE NOT NULL,
  expires_at DATE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE annual_pass_holder (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  annual_pass_id BIGINT NOT NULL,
  profile_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  UNIQUE (annual_pass_id, profile_id)
);

CREATE TABLE annual_pass_usage (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  annual_pass_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (annual_pass_id, order_id)
);

CREATE TABLE notice (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  content CLOB NOT NULL,
  display_position VARCHAR(32) NOT NULL DEFAULT 'ALL',
  priority INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
  published_at TIMESTAMP
);

CREATE TABLE operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  operator_id BIGINT,
  action VARCHAR(128) NOT NULL,
  resource VARCHAR(128),
  detail VARCHAR(1000),
  ip VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
